name: JAVA-Maven CI

on:
 push:
    branches: [ master ]
  

jobs:
  build-job: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: 14
        distribution: 'adopt'
    - run: mvn -B package --file pom.xml -DskipTests
    - run: ls 
    - run: ls target
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v1
      with:
        name: Package
        path: staging
    - run: ls staging
    
        
    
