name: JAVA-Maven CI #workflow name
#event which is triggered workflow
on:
 push:
    branches: [ master ] 
  
#runner which will run the action
jobs:
  build-job: 
    runs-on: ubuntu-latest 

    steps:
    #checkout the code from repository using actions
    - uses: actions/checkout@v1 
    - name: Set up JDK 14
      uses: actions/setup-java@v2 
      with:
        java-version: 14
        distribution: 'adopt'
 #building the maven package
    - run: mvn -B package --file pom.xml  
    - run: ls 
    - run: ls target
 # staging folder is created and all file ending with the .jar extension in the target folder is copied into staging folder   
    - run: mkdir staging && cp target/*.jar staging  
    - uses: actions/upload-artifact@v1
      with:
        name: Package
        path: staging
    - run: ls staging
    
        
    
